buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.aliyun.com/repository/central' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url = 'https://maven.aliyun.com/repository/apache-snapshots' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.blamejared.com' }
        maven { url = 'https://maven.parchmentmc.org'}
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.+'
        classpath 'org.parchmentmc:librarian:1.+'
    }
}
plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}
apply plugin: 'org.spongepowered.mixin'
group = mod_group_id
version = mod_version
base {
    archivesName = mod_id
}
java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}
minecraft {
    mappings channel: mapping_channel, version: mapping_version
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }
        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }
        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}
apply plugin: 'java'
mixin {
    add sourceSets.main, 'miztinker.refmap.json'
    config 'miztinker.mixins.json'
    debug.verbose = true
    debug.export = true
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = 'https://maven.aliyun.com/repository/central' }
    maven { url = 'https://maven.aliyun.com/repository/public' }
    maven { url = 'https://maven.aliyun.com/repository/gradle-plugin' }
    maven { url = 'https://maven.aliyun.com/repository/apache-snapshots' }
    maven { url = 'https://maven.blamejared.com' }
    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
}
dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    implementation fg.deobf("curse.maven:jei-238222:6075247")

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'

    implementation fg.deobf("curse.maven:yellowbrosss-extras-836959:5955721")

    implementation fg.deobf("curse.maven:pehkui-319596:5393101")

    implementation fg.deobf("curse.maven:geckolib-388172:7025129")

    //吸血鬼
    implementation fg.deobf("curse.maven:vampirism-become-a-vampire-233029:6289561")

    implementation fg.deobf("curse.maven:etst-lib-1206379:7044917")

    //血族工匠
    implementation fg.deobf("curse.maven:vampirism-tinker-1314650:6814093")
//领域
    implementation fg.deobf("curse.maven:tcondiadema-1218668:6862342")

    implementation fg.deobf("curse.maven:irons-spells-n-spellbooks-855414:6970299")

    implementation fg.deobf("curse.maven:projecte-226410:4901949")


    //tic
    implementation fg.deobf("curse.maven:mantle-74924:6819217")
    implementation fg.deobf("curse.maven:tinkers-construct-74072:6777068")

    implementation fg.deobf("curse.maven:slashblade-resharped-1022428:7073488")

    implementation fileTree("lib")

    implementation fileTree("lib")


    implementation fg.deobf("curse.maven:prinegorerouse-1220777:6733132")

    implementation fg.deobf("curse.maven:sjap-310187:7039817")

    implementation "curse.maven:playeranimator-658587:7066603"

    implementation fg.deobf("curse.maven:momotinker-1224077:7024699")

    implementation fg.deobf("curse.maven:goety-586095:7112220")


}
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                             mod_authors         : mod_authors, mod_description: mod_description,
                             'Agent-Class'             : "com.mizi.miztinker.agent.LxAgent",
                             'Premain-Class'           : "com.mizi.miztinker.agent.LxAgentLoader",
                             "Can-Redefine-Classes"    : "true",
                             "Can-Retransform-Classes" : "true"
                             ,]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : mod_authors,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "Can-Redefine-Classes"    : "true",
                "Can-Retransform-Classes" : "true"
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}